name: vexana
description: Manage your network layer with dio. You will be able to use it very
  easily network operations.
version: 3.3.1
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0

  # Core
  dio: ^4.0.4
  flutter:
    sdk: flutter
  logger: ^1.0.0
  connectivity_plus: ^2.3.5
  lottie: ^2.1.0

  # Database
  path_provider: ^2.0.1

  # Utility
  retry: ^3.1.0
  sembast: ^3.3.1+1
  sembast_web: ^2.0.1+1
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0

flutter:
  assets:
    - assets/lottie/
