name: vexana
description: flutter network helper project..
version: 1.1.0
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
